server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://176.122.165.184:3306/crazyloongcat?characterEncoding=UTF-8
    username: cat
    password: cat
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  jpa:
    hibernate:
      ddl-auto: update
